services:
  livekit-agent-1:
    build: .
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      # Importent when deploying multiple agents on the same livekit projects
      - AGENT_NAME=agent-1
    volumes:
      - livekit_plugin_cache:/root/.cache
      - ./agents/agent-1.py:/app/src/agent.py
    # network_mode: host

volumes:
  livekit_plugin_cache:
